version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Skip installing problematic packages
      - sudo apt-get update
      - sudo apt-get install -y libatk1.0-0 libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 || echo "Some dependencies not found"
      - npm install
  build:
    commands:
      - npm run cypress:run # Change to match your test run script
