version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing Cypress...
      - npx cypress install # Explicitly install Cypress
  build:
    commands:
      - echo Running Cypress tests...
      - chmod +x ./node_modules/.bin/cypress
      - npx cypress run --headless
  post_build:
    commands:
      - echo Creating results directory if it does not exist...
      - mkdir -p cypress/results
      - echo Uploading reports...
artifacts:
  files:
    - "**/*"
  base-directory: "cypress/results"
