version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing required libraries for Cypress...
      - sudo apt-get update
      - sudo apt-get install -y libatk1.0-0 libgdk-pixbuf2.0-0 libnspr4 libnss3 libxss1 libasound2 libgtk-3-0
      - echo Installing Cypress...
      - npx cypress install
  build:
    commands:
      - echo Running Cypress tests...
      - npx cypress run --headless
  post_build:
    commands:
      - echo Creating results directory if it does not exist...
      - mkdir -p cypress/results
      - echo Uploading reports...
      - cp -R cypress/results/* /codebuild/output/results/
artifacts:
  files:
    - cypress/results/*
