version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running Cypress tests...
      - npx cypress run
  post_build:
    commands:
      - echo Post-build phase
artifacts:
  files:
    - "**/*"
