version: 0.2

phases:
  install:
    commands:
      # Install dependencies and Cypress
      - npm install
      - chmod +x ./node_modules/.bin/cypress # Fix Cypress permissions
      - npx cypress install # Ensure Cypress is installed correctly

  build:
    commands:
      - node -v # Check Node.js version
      - npm -v # Check npm version
      - npx cypress run # Run Cypress tests

artifacts:
  files:
    - "**/*"
